---
abstract: 'IRC reaction bot framework'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UnazuSan
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  UnazuSan:
    file: lib/UnazuSan.pm
    version: 0.01
requires:
  AnySan: 0.10
  perl: 5.010
resources:
  bugtracker: https://github.com/Songmu/p5-UnazuSan/issues
  homepage: https://github.com/Songmu/p5-UnazuSan
  repository: git://github.com/Songmu/p5-UnazuSan.git
version: 0.01
